"""
Tests for WAF / bot-protection handling.

The failure these guard against: the scanner is served a challenge or block
page instead of the customer's site, grades that page, and the report tells the
customer their site lacks protections it actually has — or looks clean because
the real content was never seen.
"""
import asyncio
from unittest.mock import patch

import httpx
import pytest

from scanners import waf, exposure, headers, secrets, BROWSER_SCAN_HEADERS
from scanners.waf import Access
from reports.generator import _weighted_score, _unverified
from models.scan import (
    HeaderScanResult, DNSScanResult, SSLScanResult, ExposureScanResult,
)

DOMAIN = "example.test"
TS = "2026-09-22T00:00:00+00:00"

FULL_HEADERS = {
    "content-type": "text/html",
    "content-security-policy": "default-src 'self'",
    "strict-transport-security": "max-age=31536000",
    "x-frame-options": "SAMEORIGIN",
    "x-content-type-options": "nosniff",
    "referrer-policy": "no-referrer",
    "permissions-policy": "camera=()",
}

CF_CHALLENGE_200 = (
    "<!DOCTYPE html><html><head><title>Just a moment...</title></head><body>"
    "<script>window._cf_chl_opt={cvId:'3'};</script></body></html>"
)


def resp(status: int, headers: dict | None = None, text: str = "<html><body>ok</body></html>",
         url: str = f"https://{DOMAIN}/") -> httpx.Response:
    headers = {"content-type": "text/html", **(headers or {})}
    return httpx.Response(status, headers=headers, text=text, request=httpx.Request("GET", url))


def run(coro):
    return asyncio.run(coro)


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("response, vendor", [
    (resp(403, {"cf-mitigated": "challenge"}), "Cloudflare"),
    (resp(200, text=CF_CHALLENGE_200), "Cloudflare"),               # a challenge served as HTTP 200
    (resp(405, {"x-amzn-waf-action": "captcha"}), "AWS WAF"),
    (resp(403, text="<p>Request unsuccessful. Incapsula incident ID: 123</p>"), "Imperva"),
    (resp(403, text="<a href='https://errors.edgesuite.net/18.1'>Reference</a>"), "Akamai"),
    (resp(403, text="<title>Sucuri WebSite Firewall - Access Denied</title>"), "Sucuri"),
    (resp(503, text="<p>Generated by Wordfence at Mon</p>"), "Wordfence"),
])
def test_vendor_challenge_pages_are_recognised(response, vendor):
    assert waf.waf_vendor(response) == vendor
    assert waf.block_reason(response) is not None


@pytest.mark.parametrize("text", [
    # Cloudflare injects this detection script into ordinary pages behind it.
    '<html><script src="/cdn-cgi/challenge-platform/h/b/scripts/jsd/main.js"></script><h1>Shop</h1></html>',
    # A single-page app shell is not a challenge, however little it contains.
    '<html><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></html>',
])
def test_ordinary_pages_behind_a_waf_are_not_mistaken_for_challenges(text):
    page = resp(200, text=text)
    assert waf.waf_vendor(page) is None
    assert waf.block_reason(page) is None


def test_plain_refusal_status_is_a_block_without_a_vendor():
    refused = resp(403, text="Forbidden")
    assert waf.waf_vendor(refused) is None
    assert "HTTP 403" in waf.block_reason(refused)


# ---------------------------------------------------------------------------
# Access probe
# ---------------------------------------------------------------------------

def _homepage(scanner, browser):
    async def fake(domain, request_headers):
        r = browser if request_headers["User-Agent"] == BROWSER_SCAN_HEADERS["User-Agent"] else scanner
        if isinstance(r, Exception):
            raise r
        return r
    return patch.object(waf, "_get_homepage", fake)


def test_challenge_to_scanner_is_retried_as_a_browser():
    with _homepage(resp(200, text=CF_CHALLENGE_200), resp(200, FULL_HEADERS)):
        access = run(waf.probe_access(DOMAIN))
    assert access.blocked is None
    assert access.client == "browser"
    assert access.request_headers["User-Agent"] == BROWSER_SCAN_HEADERS["User-Agent"]


def test_challenge_to_both_clients_is_reported_not_graded():
    with _homepage(resp(403, {"cf-mitigated": "challenge"}), resp(403, {"cf-mitigated": "challenge"})):
        access = run(waf.probe_access(DOMAIN))
    assert access.response is None
    assert "Cloudflare" in access.blocked


def test_a_block_reason_is_kept_over_a_later_network_error():
    with _homepage(resp(403, {"cf-mitigated": "challenge"}), httpx.ConnectTimeout("slow")):
        access = run(waf.probe_access(DOMAIN))
    assert "Cloudflare" in access.blocked


# ---------------------------------------------------------------------------
# Scanners never grade or claim anything from a refused scan
# ---------------------------------------------------------------------------

BLOCKED = Access(None, {"User-Agent": "x"}, "scanner", "Cloudflare answered with a bot-protection page (HTTP 403).")


class _NoNetwork:
    def __init__(self, *a, **k):
        raise AssertionError("a refused scan must not send further requests")


def test_headers_are_unverified_not_missing_when_refused():
    result = run(headers.scan_headers(DOMAIN, BLOCKED))
    assert result.findings == []
    assert result.summary["verified"] is False
    assert "Cloudflare" in result.summary["error"]


def test_exposure_sends_no_probes_when_refused():
    with patch.object(exposure.httpx, "AsyncClient", _NoNetwork):
        result = run(exposure.scan_exposure(DOMAIN, BLOCKED))
    assert result.findings == []
    assert result.summary["verified"] is False


def test_secrets_reads_nothing_when_refused():
    with patch.object(secrets.httpx, "AsyncClient", _NoNetwork):
        result = run(secrets.scan_secrets(DOMAIN, BLOCKED))
    assert result.files_scanned == 0
    assert result.summary["verified"] is False


def test_headers_graded_from_the_real_page_when_reached():
    access = Access(resp(200, FULL_HEADERS), dict(BROWSER_SCAN_HEADERS), "browser", None)
    result = run(headers.scan_headers(DOMAIN, access))
    assert sum(1 for f in result.findings if f.status == "missing") == 0
    assert result.summary["client"] == "browser"


# ---------------------------------------------------------------------------
# Exposure: a WAF 403 is not the site's configuration
# ---------------------------------------------------------------------------

class _OneResponseClient:
    def __init__(self, response):
        self._response = response

    async def get(self, url):
        return self._response


ENV_PROBE = next(p for p in exposure._PROBES if p["path"] == "/.env")


def test_waf_answer_to_a_probe_makes_no_claim_about_the_path():
    refused: list[str] = []
    finding = run(exposure._probe(_OneResponseClient(resp(403, {"cf-mitigated": "block"})),
                                  f"https://{DOMAIN}", ENV_PROBE, refused=refused))
    assert finding is None
    assert refused == ["/.env"]


def test_the_sites_own_403_is_still_reported_as_blocked():
    finding = run(exposure._probe(_OneResponseClient(resp(403, text="Forbidden")),
                                  f"https://{DOMAIN}", ENV_PROBE, refused=[]))
    assert finding is not None and finding.exposed is False and "blocked" in finding.label


# ---------------------------------------------------------------------------
# Overall score
# ---------------------------------------------------------------------------

def _results(header_summary: dict):
    h = HeaderScanResult(domain=DOMAIN, scanned_url="", scan_timestamp=TS, findings=[], information_leaks=[],
                         risk_score=0, risk_level="low", summary=header_summary)
    d = DNSScanResult(domain=DOMAIN, scan_timestamp=TS, records=[], findings=[], risk_score=40,
                      risk_level="high", summary={})
    s = SSLScanResult(domain=DOMAIN, port=443, scan_timestamp=TS, certificate=None, tls_versions=[],
                      findings=[], risk_score=40, risk_level="high", summary={})
    e = ExposureScanResult(domain=DOMAIN, scan_timestamp=TS, findings=[], risk_score=40,
                           risk_level="high", summary={})
    return h, d, s, e


def test_unverified_scanner_does_not_pull_the_score_down():
    h, d, s, e = _results({"verified": False, "error": "refused"})
    unseen = _weighted_score(h, d, s, e)

    # Treating the unseen headers as a perfect 0 would give this (the old behaviour).
    as_if_perfect = round(40 * (0.28 + 0.22 + 0.17))
    # Leaving them out should score as if headers matched the scanners we did see.
    h_matching = h.model_copy(update={"risk_score": 40, "summary": {}})
    as_if_matching = _weighted_score(h_matching, d, s, e)

    assert unseen > as_if_perfect
    assert unseen == as_if_matching


def test_score_unchanged_when_everything_is_verified():
    h, d, s, e = _results({})
    expected = round(40 * (0.28 + 0.22 + 0.17))
    assert _weighted_score(h, d, s, e) == expected


def test_unverified_scanners_are_named_in_the_report():
    h, d, s, e = _results({"verified": False, "error": "Cloudflare answered with a bot-protection page."})
    assert _unverified(headers=h, exposure=e) == {"headers": "Cloudflare answered with a bot-protection page."}


# ---------------------------------------------------------------------------
# Protection observed in front of the site (reported as context, never scored)
# ---------------------------------------------------------------------------

from models.scan import EdgeProtection
from reports.action_plan import _protection_note, build_action_plan
from reports.html_report import generate_action_plan_html


def test_routing_header_identifies_the_edge_network():
    assert waf.edge_vendor(resp(200, {"cf-ray": "8c1-SEA"})) == "Cloudflare"
    assert waf.edge_vendor(resp(200, {"server": "AkamaiGHost"})) == "Akamai"
    assert waf.edge_vendor(resp(200, {"server": "nginx"})) is None


def test_challenge_to_the_scanner_is_evidence_even_when_the_browser_gets_through():
    with _homepage(resp(200, text=CF_CHALLENGE_200), resp(200, {**FULL_HEADERS, "cf-ray": "x"})):
        access = run(waf.probe_access(DOMAIN))
    assert access.protection == EdgeProtection(vendor="Cloudflare", evidence="challenge", blocked=False)


def test_challenge_to_both_clients_is_recorded_as_blocking():
    with _homepage(resp(403, {"cf-mitigated": "challenge"}), resp(403, {"cf-mitigated": "challenge"})):
        access = run(waf.probe_access(DOMAIN))
    assert access.protection.evidence == "challenge" and access.protection.blocked


def test_routed_but_unchallenged_is_only_edge_evidence():
    with _homepage(resp(200, {**FULL_HEADERS, "cf-ray": "x"}), resp(200, FULL_HEADERS)):
        access = run(waf.probe_access(DOMAIN))
    assert access.protection == EdgeProtection(vendor="Cloudflare", evidence="edge")


def test_no_protection_claimed_for_a_plain_site():
    with _homepage(resp(200, FULL_HEADERS), resp(200, FULL_HEADERS)):
        access = run(waf.probe_access(DOMAIN))
    assert access.protection is None


def test_vendor_answering_sensitive_paths_upgrades_edge_to_rules():
    access = Access(resp(200), {}, "scanner", None, EdgeProtection(vendor="Cloudflare", evidence="edge"))
    p = waf.observed_protection(access, {"waf_blocked": {"/.env": "Cloudflare", "/.git/HEAD": "Cloudflare"}})
    assert p.evidence == "rules" and p.paths == ["/.env", "/.git/HEAD"]


def test_a_challenge_is_not_downgraded_by_path_evidence():
    access = Access(resp(200), {}, "browser", None, EdgeProtection(vendor="Cloudflare", evidence="challenge"))
    assert waf.observed_protection(access, {"waf_blocked": {"/.env": "Cloudflare"}}).evidence == "challenge"


def test_only_sensitive_paths_count_as_firewall_evidence():
    robots = next(p for p in exposure._PROBES if p["path"] == "/robots.txt")
    challenge = resp(403, {"cf-mitigated": "challenge"})
    answered: dict[str, str] = {}
    for probe in (ENV_PROBE, robots):
        run(exposure._probe(_OneResponseClient(challenge), f"https://{DOMAIN}", probe, refused=[], answered_by=answered))
    assert answered == {"/.env": "Cloudflare"}


def _with_protection(p):
    import test_action_plan as ta
    return ta.make_result(protection=p)


def test_edge_wording_never_claims_the_firewall_is_on():
    note = _protection_note(_with_protection(EdgeProtection(vendor="Cloudflare", evidence="edge")), 4)
    assert "served through Cloudflare" in note
    assert "cannot be confirmed" in note
    assert "active" not in note and "protected" not in note


@pytest.mark.parametrize("p, expected", [
    (EdgeProtection(vendor="Cloudflare", evidence="challenge"), "Cloudflare bot protection is active"),
    (EdgeProtection(vendor="Cloudflare", evidence="challenge", blocked=True), "marked incomplete on page 4"),
    (EdgeProtection(vendor="Sucuri", evidence="rules", paths=["/.env"]), "Sucuri's firewall is active on this site: it answered our requests for sensitive paths (/.env)"),
])
def test_note_states_what_was_observed(p, expected):
    assert expected in _protection_note(_with_protection(p), 4)


def test_note_appears_on_the_owner_brief_and_is_labelled_not_scored():
    result = _with_protection(EdgeProtection(vendor="Cloudflare", evidence="challenge"))
    html = generate_action_plan_html(result)
    first_page = html.split('class="sheet"')[1]
    assert "Cloudflare bot protection is active" in first_page
    assert "Not scored" in first_page


def test_no_note_when_nothing_was_observed():
    assert build_action_plan(_with_protection(None)).protection_note is None
