"""
Detects when a site answers with a WAF or bot-protection page instead of itself.

Grading that page as the customer's site produces false findings in both
directions: protections reported missing that the real page sets, and "nothing
found" where the real content was never seen. This module only detects and
reports. It never attempts to solve a challenge (no JavaScript execution, no
cookie replay), because that is a bypass technique and out of bounds.
"""

from dataclasses import dataclass
import httpx
from scanners import SCAN_HEADERS, BROWSER_SCAN_HEADERS, BLOCKED_STATUSES

_TIMEOUT = 10.0
_BODY_SNIFF = 20_000

# Set by the vendor on mitigation responses only, never on a normally served page.
_HEADER_MARKERS: tuple[tuple[str, str], ...] = (
    ("cf-mitigated", "Cloudflare"),
    ("x-amzn-waf-action", "AWS WAF"),
    ("x-vercel-mitigated", "Vercel"),
)

# Strings that appear on the vendor's challenge or block page and not on ordinary
# pages behind it. Deliberately excludes markers vendors inject into every page
# (e.g. Cloudflare's /cdn-cgi/challenge-platform/ detection script) and generic
# "enable JavaScript" text, which single-page apps legitimately serve.
_BODY_MARKERS: tuple[tuple[str, str], ...] = (
    ("_cf_chl_opt", "Cloudflare"),
    ("Attention Required! | Cloudflare", "Cloudflare"),
    ('id="cf-error-details"', "Cloudflare"),
    ("Incapsula incident ID", "Imperva"),
    ("errors.edgesuite.net", "Akamai"),
    ("Sucuri WebSite Firewall - Access Denied", "Sucuri"),
    ("captcha-delivery.com", "DataDome"),
    ("px-captcha", "HUMAN (PerimeterX)"),
    ("Generated by Wordfence", "Wordfence"),
)


def waf_vendor(response: httpx.Response) -> str | None:
    """Name of the protection vendor if this response is its challenge or block page."""
    for header, vendor in _HEADER_MARKERS:
        if header in response.headers:
            return vendor
    ctype = response.headers.get("content-type", "").lower()
    if ctype and "html" not in ctype and "text" not in ctype:
        return None
    try:
        body = response.text[:_BODY_SNIFF]
    except Exception:
        return None
    for marker, vendor in _BODY_MARKERS:
        if marker in body:
            return vendor
    return None


def block_reason(response: httpx.Response) -> str | None:
    """Why this response is not the site's real page, or None if it is."""
    vendor = waf_vendor(response)
    if vendor:
        return (
            f"{vendor} answered with a bot-protection page (HTTP {response.status_code}) instead of "
            "the site, so what a visitor receives could not be observed."
        )
    if response.status_code in BLOCKED_STATUSES:
        return (
            f"The site refused the scan (HTTP {response.status_code}), so what a visitor receives "
            "could not be observed."
        )
    return None


@dataclass
class Access:
    """The outcome of reaching a site's homepage, shared by every page-reading scanner."""
    response: httpx.Response | None
    request_headers: dict[str, str]
    client: str                  # "scanner" or "browser"
    blocked: str | None          # reason the real page was not reached; None when it was


async def _get_homepage(domain: str, request_headers: dict[str, str]) -> httpx.Response:
    async with httpx.AsyncClient(follow_redirects=True, timeout=_TIMEOUT, headers=request_headers) as client:
        try:
            return await client.get(f"https://{domain}")
        except httpx.ConnectError:
            return await client.get(f"http://{domain}")


async def probe_access(domain: str) -> Access:
    """
    Fetch the homepage as the identified scanner; if refused, retry once as a
    standard browser, which receives exactly what any visitor does. If that is
    refused too, report the block and stop there.
    """
    blocked: str | None = None
    unreachable: str | None = None
    for client_name, request_headers in (("scanner", SCAN_HEADERS), ("browser", BROWSER_SCAN_HEADERS)):
        try:
            response = await _get_homepage(domain, dict(request_headers))
        except Exception as exc:
            unreachable = f"The site could not be reached: {str(exc) or type(exc).__name__}."
            continue
        reason = block_reason(response)
        if reason is None:
            return Access(response, dict(request_headers), client_name, None)
        blocked = reason  # keep the most visitor-like attempt's reason
    return Access(None, dict(SCAN_HEADERS), "scanner", blocked or unreachable)
