"""
Detects when a site answers with a WAF or bot-protection page instead of itself.

Grading that page as the customer's site produces false findings in both
directions: protections reported missing that the real page sets, and "nothing
found" where the real content was never seen. This module only detects and
reports. It never attempts to solve a challenge (no JavaScript execution, no
cookie replay), because that is a bypass technique and out of bounds.
"""

from dataclasses import dataclass
import httpx
from models.scan import EdgeProtection
from scanners import SCAN_HEADERS, BROWSER_SCAN_HEADERS, BLOCKED_STATUSES

_TIMEOUT = 10.0
_BODY_SNIFF = 20_000

# Set by the vendor on mitigation responses only, never on a normally served page.
_HEADER_MARKERS: tuple[tuple[str, str], ...] = (
    ("cf-mitigated", "Cloudflare"),
    ("x-amzn-waf-action", "AWS WAF"),
    ("x-vercel-mitigated", "Vercel"),
)

# Strings that appear on the vendor's challenge or block page and not on ordinary
# pages behind it. Deliberately excludes markers vendors inject into every page
# (e.g. Cloudflare's /cdn-cgi/challenge-platform/ detection script) and generic
# "enable JavaScript" text, which single-page apps legitimately serve.
_BODY_MARKERS: tuple[tuple[str, str], ...] = (
    ("_cf_chl_opt", "Cloudflare"),
    ("Attention Required! | Cloudflare", "Cloudflare"),
    ('id="cf-error-details"', "Cloudflare"),
    ("Incapsula incident ID", "Imperva"),
    ("errors.edgesuite.net", "Akamai"),
    ("Sucuri WebSite Firewall - Access Denied", "Sucuri"),
    ("captcha-delivery.com", "DataDome"),
    ("px-captcha", "HUMAN (PerimeterX)"),
    ("Generated by Wordfence", "Wordfence"),
)


# Present on ordinary responses served through the vendor's network. They show
# the traffic passes through the vendor, not that any firewall rule is enabled.
_EDGE_HEADERS: tuple[tuple[str, str], ...] = (
    ("cf-ray", "Cloudflare"),
    ("x-sucuri-id", "Sucuri"),
    ("x-iinfo", "Imperva"),
)
_EDGE_SERVER_TOKENS: tuple[tuple[str, str], ...] = (
    ("cloudflare", "Cloudflare"),
    ("akamaighost", "Akamai"),
    ("sucuri", "Sucuri"),
)


def edge_vendor(response: httpx.Response) -> str | None:
    """Name of the security edge network the response was served through, if any."""
    for header, vendor in _EDGE_HEADERS:
        if header in response.headers:
            return vendor
    server = response.headers.get("server", "").lower()
    for token, vendor in _EDGE_SERVER_TOKENS:
        if token in server:
            return vendor
    x_cdn = response.headers.get("x-cdn", "").lower()
    if "imperva" in x_cdn or "incapsula" in x_cdn:
        return "Imperva"
    return None


def waf_vendor(response: httpx.Response) -> str | None:
    """Name of the protection vendor if this response is its challenge or block page."""
    for header, vendor in _HEADER_MARKERS:
        if header in response.headers:
            return vendor
    ctype = response.headers.get("content-type", "").lower()
    if ctype and "html" not in ctype and "text" not in ctype:
        return None
    try:
        body = response.text[:_BODY_SNIFF]
    except Exception:
        return None
    for marker, vendor in _BODY_MARKERS:
        if marker in body:
            return vendor
    return None


def block_reason(response: httpx.Response) -> str | None:
    """Why this response is not the site's real page, or None if it is."""
    vendor = waf_vendor(response)
    if vendor:
        return (
            f"{vendor} answered with a bot-protection page (HTTP {response.status_code}) instead of "
            "the site, so what a visitor receives could not be observed."
        )
    if response.status_code in BLOCKED_STATUSES:
        return (
            f"The site refused the scan (HTTP {response.status_code}), so what a visitor receives "
            "could not be observed."
        )
    return None


@dataclass
class Access:
    """The outcome of reaching a site's homepage, shared by every page-reading scanner."""
    response: httpx.Response | None
    request_headers: dict[str, str]
    client: str                  # "scanner" or "browser"
    blocked: str | None          # reason the real page was not reached; None when it was
    protection: EdgeProtection | None = None


async def _get_homepage(domain: str, request_headers: dict[str, str]) -> httpx.Response:
    async with httpx.AsyncClient(follow_redirects=True, timeout=_TIMEOUT, headers=request_headers) as client:
        try:
            return await client.get(f"https://{domain}")
        except httpx.ConnectError:
            return await client.get(f"http://{domain}")


async def probe_access(domain: str) -> Access:
    """
    Fetch the homepage as the identified scanner; if refused, retry once as a
    standard browser, which receives exactly what any visitor does. If that is
    refused too, report the block and stop there.
    """
    blocked: str | None = None
    unreachable: str | None = None
    challenged_by: str | None = None
    last: httpx.Response | None = None
    for client_name, request_headers in (("scanner", SCAN_HEADERS), ("browser", BROWSER_SCAN_HEADERS)):
        try:
            response = await _get_homepage(domain, dict(request_headers))
        except Exception as exc:
            unreachable = f"The site could not be reached: {str(exc) or type(exc).__name__}."
            continue
        last = response
        # A challenge to the identified scanner is evidence that bot protection is
        # on, even when the browser retry is then let through.
        challenged_by = challenged_by or waf_vendor(response)
        reason = block_reason(response)
        if reason is None:
            return Access(response, dict(request_headers), client_name, None,
                          _protection(challenged_by, response, blocked=False))
        blocked = reason  # keep the most visitor-like attempt's reason
    return Access(None, dict(SCAN_HEADERS), "scanner", blocked or unreachable,
                  _protection(challenged_by, last, blocked=True))


def _protection(challenged_by: str | None, response: httpx.Response | None, blocked: bool) -> EdgeProtection | None:
    if challenged_by:
        return EdgeProtection(vendor=challenged_by, evidence="challenge", blocked=blocked)
    vendor = edge_vendor(response) if response is not None else None
    return EdgeProtection(vendor=vendor, evidence="edge", blocked=blocked) if vendor else None


def observed_protection(access: Access, exposure_summary: dict) -> EdgeProtection | None:
    """
    Combine the homepage probe with the exposure probes. A vendor answering our
    requests for /.env or /.git is stronger evidence than a routing header, so it
    upgrades an "edge" observation to "rules".
    """
    answered = exposure_summary.get("waf_blocked") or {}
    if answered and (access.protection is None or access.protection.evidence == "edge"):
        return EdgeProtection(vendor=next(iter(answered.values())), evidence="rules", paths=sorted(answered))
    return access.protection
